# Generated by Django 2.1.5 on 2019-01-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField()),
                ('comment_text', models.TextField()),
                ('praise', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'label',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=50)),
                ('singer_img', models.URLField()),
                ('album_img', models.URLField()),
                ('singer_info', models.TextField()),
                ('singer_fans', models.CharField(max_length=20)),
                ('singer_albums', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'singer',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=20)),
                ('song_name', models.CharField(max_length=50)),
                ('song_img', models.URLField()),
                ('song_lyrics', models.TextField()),
                ('song_album', models.CharField(max_length=50)),
                ('song_time', models.TimeField()),
                ('song_date', models.DateField()),
                ('song_url', models.URLField(max_length=150)),
                ('play_num', models.IntegerField()),
                ('download_num', models.IntegerField()),
                ('is_free', models.BooleanField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymusic.Label')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymusic.Singer')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('userpwd', models.CharField(max_length=20)),
                ('usertel', models.CharField(max_length=20)),
                ('user_sex', models.CharField(max_length=20)),
                ('is_staff', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
            ],
            options={
                'db_table': 'wheel',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymusic.Songs'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymusic.User'),
        ),
        migrations.AddField(
            model_name='collections',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymusic.Songs'),
        ),
        migrations.AddField(
            model_name='collections',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymusic.User'),
        ),
    ]
