# Generated by Django 2.1.5 on 2019-01-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='label',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='singer',
        ),
        migrations.DeleteModel(
            name='Wheel',
        ),
        migrations.DeleteModel(
            name='Collections',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
