# Generated by Django 2.1.5 on 2019-01-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
